version: "3"

services:
  nginx:
      build: ./nginx
      ports:
          - "80:80"
      restart: always
  #db:
  #  image: postgres:9.5
  #  environment:
  #    - POSTGRES_USER=${MY_APP_DATABASE_USER}
  #    - POSTGRES_PASSWORD=${MY_APP_DATABASE_PASSWORD}
  #    - POSTGRES_DB=${MY_APP_DATABASE_NAME}
  rails:
    #build:
    #  context: .
    images: localhost:5000/temy13/bookrep:v1
    ports:
      - "3000:${PORT:-3000}"
    environment:
      #- DATABASE_URL=postgres://${MY_APP_DATABASE_USER}:${MY_APP_DATABASE_PASSWORD}@db:5432/${MY_APP_DATABASE_NAME}
      - DATABASE_URL=postgres://${MY_APP_DATABASE_USER}:${MY_APP_DATABASE_PASSWORD}@${MY_APP_DATABASE_HOST}:5432/${MY_APP_DATABASE_NAME}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
    #depends_on:
    #  - db
